### PR TITLE
Merge multiple rules into one rule if they have the same destinations

### PR DESCRIPTION
**Pull request by zhengxiexie**
When expand rules for named-port and non-named-port, we should merge the multiple service entries into one rule.
e.g.
          Src  Dst Services
ruleA: Any Any TCP (Source: Any | Destination: 80-8888) 
ruleB: Any Any TCP (Source: Any | Destination: 9999)
 ----->
          Src  Dst Services
rule:   Any Any TCP (Source: Any | Destination: 80-8888)
************** TCP (Source: Any | Destination: 9999)

However,
          Src  Dst Services
ruleA: Any IPSetGroup1 TCP (Source: Any | Destination: 80-8888) 
ruleB: Any IPSetGroup2 TCP (Source: Any | Destination: 9999) 
Can't merge since the Destinations are different.

### CODE REVIEW

**Comment by zhengxiexie** [comment]
Tests Done
1. non-named-port security policy
apiVersion: nsx.vmware.com/v1alpha1
kind: SecurityPolicy
metadata:
  name: named-port-policy
  namespace: web
spec:
  priority: 10
  appliedTo:
    - podSelector:
        matchLabels:
          role: web
  rules:
    - direction: in
      action: allow
      ports:
        - protocol: TCP
          port: 80
          endPort: 8888
        - protocol: TCP
          port: 9999
image
2. named-port policy with different destinations
test/e2e/testSecurityPolicy/rule-out-rule-applied-to-with-dst-with-dup-port-multi.yaml
image
2. named-port policy with same destinations
test/e2e/testSecurityPolicy/rule-out-rule-applied-to-with-dst-with-dup-port.yaml
image

**Comment by timdengyun** [comment]
For this case, named-port policy with same destinations test/e2e/testSecurityPolicy/rule-out-rule-applied-to-with-dst-with-dup-port.yaml 
There is only one port number after parsing named port, so there is only one ip set group generated.

**Review by timdengyun — APPROVED** [review]

**Pull request merged**
