### PR TITLE
remove applied to namespace

### PR DESCRIPTION
**Pull request by lxiaopei**
As discussed, we will remove appliedToNamespaces filed in
    VPCNetworkConfiguration CR, a label “nsx.vmware.com/vpc-network-configuration” will be added on Namespace
    to specify the VPCNetworkConfiguration it uses.

### CODE REVIEW

**Review by jianjuns — APPROVED** [review]
Could you define the NS label too?

**Comment by lxiaopei** [comment]
> Could you define the NS label too?

How about "ncp/vpc_network_config_crd" for the label added on Namespace to specify the VPCNetworkConfiguration CR name?

**Comment by jianjuns** [comment]
> > Could you define the NS label too?
> 
> How about "ncp/vpc_network_config_crd" for the label added on Namespace to specify the VPCNetworkConfiguration CR name?

Again, please never use "ncp". Something like "nsx.vmware.com/vpc-network-configuration"

**Comment by lxiaopei** [comment]
OK, thanks Jianjun.

**Review by heypnus — APPROVED** [review]

**Pull request merged**
