### PR TITLE
Integrate Codecov into CI pipeline

### PR DESCRIPTION
**Pull request by wenqiq**
Integrate Codecov into CI pipeline
Uploaded coverage to Codecov
Viewed coverage reports in pull requests

### CODE REVIEW

**Review by seanpang-vmware — APPROVED** [review]

**Comment by zhengxiexie** [comment]
Better to squash into 1 commit.

**Comment by zhengxiexie** [comment]
[2024-09-19T09:02:23.191Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-3.1.6-uploader-0.8.0&token=*******&branch=topic%2Fwenqi%2Fadd-code-cov&build=10937728090&build_url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Fnsx-operator%2Factions%2Fruns%2F10937728090%2Fjob%2F30364247425&commit=b7c94161d8533869b4c1dbd75ad38bd0fa8df0e1&job=Makefile+CI&pr=745&service=github-actions&slug=vmware-tanzu%2Fnsx-operator&name=codecov-unit-test&tag=&flags=unit-tests&parent=
[2024-09-19T09:02:23.553Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 429 - {'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 656s.', code='throttled')}

Can't view?

**Review by zhengxiexie — APPROVED** [review]
LGTM

**Comment by wenqiq** [comment]
https://github.com/vmware-tanzu/nsx-operator/actions/runs/11008722060/job/30566910250

**Pull request merged**
