### PR TITLE
Add e2e test for Subnet

### PR DESCRIPTION
**Pull request by jwsui**
Changes include:
1. Add CRD clientset to perform CRUD of CRDs.
2. Add SubnetSet test cases.

### CODE REVIEW

**Review by dantingl — APPROVED** [review]
LGTM

**Comment by zhengxiexie** [comment]
run e2e

**Comment by zhengxiexie** [comment]
e2e

**Comment by zhengxiexie** [comment]
pls commit a PR for https://gitlab.eng.vmware.com/nsx-ujo/nsx-operator-ci/-/blob/main/main.py#L366

**Review by zhengxiexie — APPROVED** [review]
LGTM

**Comment by jwsui** [comment]
https://github.com/vmware-tanzu/nsx-operator/pull/422

Create a new PR, closing this one.

**Pull request closed without merging**
