### PR TITLE
Replace logger in e2e test

### PR DESCRIPTION
**Pull request by zhengxiexie**
When running e2e, it groans `log.SetLogger(...) was never called; logs will not be displayed.`
```
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 25 [running]:
	>  runtime/debug.Stack()
	>  	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.9.linux-amd64/src/runtime/debug/stack.go:24 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc0003b09c0, 0x10?)
	>  	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/log/deleg.go:111 +0x32
	>  github.com/go-logr/logr.Logger.Info({{0x22e8970?, 0xc0003b09c0?}, 0x1fd770c?}, {0x1fec559, 0x12}, {0xc00034e220, 0x2, 0x2})
	>  	/root/go/pkg/mod/github.com/go-logr/logr@v1.3.0/logr.go:280 +0x72
	>  github.com/vmware-tanzu/nsx-operator/pkg/nsx.(*Endpoint).keepAlive(0xc00022d600)
	>  	/root/nsx-operator/pkg/nsx/endpoint.go:133 +0x30c
	>  github.com/vmware-tanzu/nsx-operator/pkg/nsx.(*Endpoint).KeepAlive(0xc00022d600)
	>  	/root/nsx-operator/pkg/nsx/endpoint.go:189 +0x29
	>  created by github.com/vmware-tanzu/nsx-operator/pkg/nsx.NewCluster in goroutine 1
	>  	/root/nsx-operator/pkg/nsx/cluster.go:102 +0x60b
```
As the e2e framework was cloned from somewhere, there are still stale codes, such as setupLogging func never beening used.

We can use pkg/logger instead, since it is used in controller.

Testing done:
```
2024-05-29 06:35:05,845 INFO util.py:26 b'2024-05-29 06:35:05.844\t\x1b[31mLEVEL(-2)\x1b[0m\treceived HTTP response\t{"response": "{\\n  \\"node_version\\": \\"4.2.0.0.0.23609654\\",\\n  \\"product_version\\": \\"4.2.0.0.0.23609626\\"\\n}"}'
2024-05-29 06:35:05,845 INFO util.py:26 b'2024-05-29 06:35:05.844\t\x1b[35mDEBUG\x1b[0m\tcreate serverUrl\t{"serverUrl": "https://10.173.82.65/"}'
2024-05-29 06:35:05,845 INFO util.py:26 b'2024-05-29 06:35:05.845\t\x1b[35mDEBUG\x1b[0m\tget version\t{"url": "https://10.173.82.65/api/v1/node/version"}'
2024-05-29 06:35:06,481 INFO util.py:26 b'2024-05-29 06:35:06.481\t\x1b[31mLEVEL(-2)\x1b[0m\treceived HTTP response\t{"response": "{\\n  \\"node_version\\": \\"4.2.0.0.0.23609654\\",\\n  \\"product_version\\": \\"4.2.0.0.0.23609626\\"\\n}"}'
2024-05-29 06:35:06,482 INFO util.py:26 b'2024-05-29 06:35:06.482\t\x1b[35mDEBUG\x1b[0m\tcreate serverUrl\t{"serverUrl": "https://10.173.82.65/"}'
2024-05-29 06:35:06,482 INFO util.py:26 b'2024-05-29 06:35:06.482\t\x1b[35mDEBUG\x1b[0m\tget version\t{"url": "https://10.173.82.65/api/v1/node/version"}'
2024-05-29 06:35:07,141 INFO util.py:26 b'2024-05-29 06:35:07.141\t\x1b[31mLEVEL(-2)\x1b[0m\treceived HTTP response\t{"response": "{\\n  \\"node_version\\": \\"4.2.0.0.0.23609654\\",\\n  \\"product_version\\": \\"4.2.0.0.0.23609626\\"\\n}"}'
2024-05-29 06:35:07,142 INFO util.py:26 b'2024-05-29 06:35:07.141\t\x1b[35mDEBUG\x1b[0m\tcreate serverUrl\t{"serverUrl": "https://10.173.82.65/"}'
2024-05-29 06:35:07,142 INFO util.py:26 b'2024-05-29 06:35:07.142\t\x1b[35mDEBUG\x1b[0m\tget version\t{"url": "https://10.173.82.65/api/v1/node/version"}'
2024-05-29 06:35:07,917 INFO util.py:26 b'2024-05-29 06:35:07.917\t\x1b[31mLEVEL(-2)\x1b[0m\treceived HTTP response\t{"response": "{\\n  \\"node_version\\": \\"4.2.0.0.0.23609654\\",\\n  \\"product_version\\": \\"4.2.0.0.0.23609626\\"\\n}"}'
2024-05-29 06:35:07,917 INFO util.py:26 b'2024/05/29 06:35:07 Collecting information about K8s cluster'
2024-05-29 06:35:07,931 INFO util.py:26 b'2024/05/29 06:35:07 Found 3 Nodes in the cluster'
2024-05-29 06:35:08,661 INFO util.py:26 b'2024/05/29 06:35:08 Failed to detect IPv4 or IPv6 Pod CIDR. Ignore.'
```
The output could display normally, and there is no error complaining `log.SetLogger(...) was never called; logs will not be displayed.`

### CODE REVIEW

**Comment by heypnus** [comment]
Please add the following info in your commit message:

1. What problem the error logic will cause (e.g. which logs will not be displayed?).
2. How your patch fix it.
3. Testing done.

**Comment by zhengxiexie** [comment]
> Please add the following info in your commit message:
> 
> 1. What problem the error logic will cause (e.g. which logs will not be displayed?).
> 2. How your patch fix it.
> 3. Testing done.

updated.

**Review by heypnus — APPROVED** [review]

**Review by dantingl — APPROVED** [review]

**Pull request merged**
