### PR TITLE
Remove VPC CRD and its manifest

### PR DESCRIPTION
**Pull request by lxiaopei**
Remove VPC type and its CRD in manifests

### CODE REVIEW

**Comment by seanpang-vmware** [comment]
need to regenerate zz_deepcopy files

**Review by zhengxiexie — APPROVED** [review]
LGTM

**Review by seanpang-vmware — APPROVED** [review]
could you also cp to v4.2.0 branch for nsx-longview42-wcp branch

**Review by zhengxiexie — APPROVED** [review]
LGTM

**Pull request merged**
