### PR TITLE
Remove ippool CRD and other stale resources

### PR DESCRIPTION
**Pull request by zhengxiexie**
Only keep nsxserviceaccount and securitypolicy in pkg/apis/nsx.vmware.com/v1alpha1/ 
Run `make generated`

### CODE REVIEW

**Comment by wenqiq** [comment]
Should we remove the e2e test cases?

**Comment by zhengxiexie** [comment]
> Should we remove the e2e test cases?

ok

**Review by dantingl — APPROVED** [review]

**Review by TaoZou1 — APPROVED** [review]

**Pull request merged**
